# path: programs/zero_trust/Cargo.toml
[package]
name = "zero_trust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.30.0"

[features]
no-entrypoint = []

